"""Increase length of image field

Revision ID: 0307d30d781e
Revises: f684be064992
Create Date: 2024-06-14 04:55:52.546552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0307d30d781e'
down_revision = 'f684be064992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sosa_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sosa_log', 'action',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('sosa_log', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
    op.alter_column('sosa_log', 'location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('materials', 'image',
               existing_type=sa.String(length=20),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sosa_log', 'location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('sosa_log', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
    op.alter_column('sosa_log', 'action',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('sosa_log', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
