"""Add explicit tablenames

Revision ID: 2ca30b372511
Revises: c3df86180841
Create Date: 2024-06-10 18:26:40.469850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ca30b372511'
down_revision = 'c3df86180841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Replace NULL values in columns with appropriate default values
    op.execute("UPDATE users SET prefecture = 'default' WHERE prefecture IS NULL")
    op.execute("UPDATE users SET city = 'default' WHERE city IS NULL")
    op.execute("UPDATE users SET address = 'default' WHERE address IS NULL")
    op.execute("UPDATE users SET company_name = 'default' WHERE company_name IS NULL")
    op.execute("UPDATE users SET company_phone = '000-0000-0000' WHERE company_phone IS NULL")
    op.execute("UPDATE users SET industry = 'default' WHERE industry IS NULL")
    op.execute("UPDATE users SET job_title = 'default' WHERE job_title IS NULL")
    op.execute("UPDATE users SET contact_name = 'default' WHERE contact_name IS NULL")
    op.execute("UPDATE users SET contact_phone = '000-0000-0000' WHERE contact_phone IS NULL")

    op.execute("UPDATE materials SET size_1 = 0.0 WHERE size_1 IS NULL")
    op.execute("UPDATE materials SET size_2 = 0.0 WHERE size_2 IS NULL")
    op.execute("UPDATE materials SET size_3 = 0.0 WHERE size_3 IS NULL")
    op.execute("UPDATE materials SET location = 'default' WHERE location IS NULL")

    op.execute("UPDATE wanted_materials SET size_1 = '0' WHERE size_1 IS NULL OR size_1 = ''")
    op.execute("UPDATE wanted_materials SET size_2 = '0' WHERE size_2 IS NULL OR size_2 = ''")
    op.execute("UPDATE wanted_materials SET size_3 = '0' WHERE size_3 IS NULL OR size_3 = ''")
    op.execute("UPDATE wanted_materials SET location = 'default' WHERE location IS NULL")

    # Alter columns to NOT NULL and change types
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('users', 'prefecture',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('users', 'company_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'industry',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'without_approval',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('users', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('materials', 'size_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('materials', 'size_2',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('materials', 'size_3',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('materials', 'deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('materials', 'image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)

    # Change data type of size columns in wanted_materials table
    op.alter_column('wanted_materials', 'size_1',
               existing_type=sa.String(length=100),
               type_=sa.Float(),
               postgresql_using="size_1::float",
               nullable=False)
    op.alter_column('wanted_materials', 'size_2',
               existing_type=sa.String(length=100),
               type_=sa.Float(),
               postgresql_using="size_2::float",
               nullable=False)
    op.alter_column('wanted_materials', 'size_3',
               existing_type=sa.String(length=100),
               type_=sa.Float(),
               postgresql_using="size_3::float",
               nullable=False)
    op.alter_column('wanted_materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('wanted_materials', 'deadline',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wanted_materials', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('wanted_materials', 'location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('wanted_materials', 'size_3',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wanted_materials', 'size_2',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wanted_materials', 'size_1',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'without_approval',
               existing_type=sa.String(length=100),
               type_=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'job_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'industry',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'company_phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'address',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'prefecture',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'company_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('materials', 'image',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('materials', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('materials', 'location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('materials', 'size_3',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('materials', 'size_2',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('materials', 'size_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
