"""Add prefecture, city, address columns to User model

Revision ID: 418f24db640a
Revises: ed4e43b97b53
Create Date: 2024-06-06 03:10:45.756477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418f24db640a'
down_revision = 'ed4e43b97b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prefecture', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=255), nullable=True))
    op.drop_column('users', 'company_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'address')
    op.drop_column('users', 'city')
    op.drop_column('users', 'prefecture')
    # ### end Alembic commands ###
