"""Add wanted_material_id to Request

Revision ID: 70e0351e5a4c
Revises: b4525de728f9
Create Date: 2024-06-04 23:00:35.869120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e0351e5a4c'
down_revision = 'b4525de728f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('wanted_material_id', sa.Integer(), nullable=True))
    op.alter_column('requests', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'requests', 'wanted_materials', ['wanted_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.alter_column('requests', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('requests', 'wanted_material_id')
    # ### end Alembic commands ###
