"""Add note to WantedMaterial

Revision ID: 75ab96814252
Revises: e1a11bb3e8d5
Create Date: 2024-06-03 02:28:23.892810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ab96814252'
down_revision = 'e1a11bb3e8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('wanted_materials', sa.Column('', sa.String(length=100), nullable=True))
    op.add_column('wanted_materials', sa.Column('finish_type', sa.String(length=100), nullable=True))
    op.add_column('wanted_materials', sa.Column('note', sa.Text(), nullable=True))
    op.alter_column('wanted_materials', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('wanted_materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wanted_materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('wanted_materials', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('wanted_materials', 'note')
    op.drop_column('wanted_materials', 'finish_type')
    op.drop_column('wanted_materials', '')
    op.alter_column('materials', 'location',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('materials', 'size',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
