"""Add completed and completed_at columns to materials table

Revision ID: b4525de728f9
Revises: 37a257004b3e
Create Date: 2024-06-04 22:33:25.126583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4525de728f9'
down_revision = '37a257004b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('materials', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'completed_at')
    op.drop_column('materials', 'completed')
    # ### end Alembic commands ###
