"""Change size fields to float

Revision ID: c3df86180841
Revises: 418f24db640a
Create Date: 2024-06-10 07:55:19.278512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3df86180841'
down_revision = '418f24db640a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE materials SET size_1 = NULL WHERE size_1 = ''")
    op.execute("UPDATE materials SET size_2 = NULL WHERE size_2 = ''")
    op.execute("UPDATE materials SET size_3 = NULL WHERE size_3 = ''")
    
    op.alter_column('materials', 'size_1',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='size_1::double precision')
    op.alter_column('materials', 'size_2',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='size_2::double precision')
    op.alter_column('materials', 'size_3',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='size_3::double precision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'size_3',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               postgresql_using='size_3::text')
    op.alter_column('materials', 'size_2',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               postgresql_using='size_2::text')
    op.alter_column('materials', 'size_1',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True,
               postgresql_using='size_1::text')
    # ### end Alembic commands ###
