"""Alter materials and wanted_materials tables to add size_1, size_2, size_3 columns and remove size column

Revision ID: dccb6a5646a7
Revises: 75ab96814252
Create Date: 2024-06-04 20:45:27.438956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccb6a5646a7'
down_revision = '75ab96814252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('size_1', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('size_2', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('size_3', sa.String(length=100), nullable=True))
    op.drop_column('materials', 'size')
    op.add_column('wanted_materials', sa.Column('size_1', sa.String(length=100), nullable=True))
    op.add_column('wanted_materials', sa.Column('size_2', sa.String(length=100), nullable=True))
    op.add_column('wanted_materials', sa.Column('size_3', sa.String(length=100), nullable=True))
    op.drop_column('wanted_materials', 'size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wanted_materials', sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('wanted_materials', 'size_3')
    op.drop_column('wanted_materials', 'size_2')
    op.drop_column('wanted_materials', 'size_1')
    op.add_column('materials', sa.Column('size', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('materials', 'size_3')
    op.drop_column('materials', 'size_2')
    op.drop_column('materials', 'size_1')
    # ### end Alembic commands ###
