"""initial migration

Revision ID: e1a11bb3e8d5
Revises: 
Create Date: 2024-06-02 14:48:12.199889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a11bb3e8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_column('materials', 'material_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('material_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_posted', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name='reviews_material_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    # ### end Alembic commands ###
def upgrade():
    op.add_column('wanted_materials', sa.Column('', sa.String(length=100), nullable=True))
    op.add_column('wanted_materials', sa.Column('finish_type', sa.String(length=100), nullable=True))


def downgrade():
    op.drop_column('wanted_materials', '')
    op.drop_column('wanted_materials', 'finish_type')