"""Remove contact_email column and update schema

Revision ID: ed4e43b97b53
Revises: 70e0351e5a4c
Create Date: 2024-06-05 23:54:16.785167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4e43b97b53'
down_revision = '70e0351e5a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_email')
    op.add_column('wanted_materials', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('wanted_materials', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wanted_materials', 'completed_at')
    op.drop_column('wanted_materials', 'completed')
    op.add_column('users', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
